name: GitHub custom action

on:
  push:
    branches:
      - develop
      - main

jobs:
  Build:
    runs-on: [self-hosted, macos]
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          github-context: ${{ toJSON(github) }}
          env-context: ${{ toJSON(env) }}
